Resources:
  RegisterFunctionServiceRoleDB8F6C89:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: BackendStack/RegisterFunction/ServiceRole/Resource
  RegisterFunction735506DF:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}
        S3Key: 04659c3523a310332b37bdae05b3b99b930329ca117888c97b494a61eb963805.zip
      Handler: register.handler
      Role:
        Fn::GetAtt:
          - RegisterFunctionServiceRoleDB8F6C89
          - Arn
      Runtime: nodejs18.x
    DependsOn:
      - RegisterFunctionServiceRoleDB8F6C89
    Metadata:
      aws:cdk:path: BackendStack/RegisterFunction/Resource
      aws:asset:path: asset.04659c3523a310332b37bdae05b3b99b930329ca117888c97b494a61eb963805
      aws:asset:is-bundled: false
      aws:asset:property: Code
  RegisterFunctionFunctionUrl2B282795:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn:
        Fn::GetAtt:
          - RegisterFunction735506DF
          - Arn
    Metadata:
      aws:cdk:path: BackendStack/RegisterFunction/FunctionUrl/Resource
  RegisterFunctioninvokefunctionurl3FA3D206:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName:
        Fn::GetAtt:
          - RegisterFunction735506DF
          - Arn
      FunctionUrlAuthType: NONE
      Principal: "*"
    Metadata:
      aws:cdk:path: BackendStack/RegisterFunction/invoke-function-url
Outputs:
  myFunctionUrlOutput:
    Value:
      Fn::GetAtt:
        - RegisterFunctionFunctionUrl2B282795
        - FunctionUrl
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

