-- Synthetic public API fixtures. Never generated from a live database.
INSERT INTO project (id, name) VALUES (1, 'Test Project');
INSERT INTO node (id, name, type, "order", parent_id, project_id) VALUES (1, 'Root', 'Root', 0, NULL, 1), (2, 'People', 'List', 0, 1, 1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (3,'Name','String',3,2,1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (4,'Age','Number',4,2,1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (5,'Birthdate','Date',5,2,1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (6,'Clothing','Color',6,2,1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (7,'Gender','Choice',7,2,1);
INSERT INTO node (id,name,type,"order",parent_id,project_id) VALUES (8,'Management','Boolean',8,2,1);
INSERT INTO node_settings (node_id,project_id,settings) VALUES (7,1,'{"choices":["Male","Female"]}');
INSERT INTO "values" (id,node_id,project_id,value,"order") VALUES (100,2,1,'{"name":"Item 0"}',0);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (103, 3,1,'{"content": "Alex Example"}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (104, 4,1,'{"figure": 48}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (105, 5,1,'{"date": "1976-11-14"}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (106, 6,1,'{"rgba": [165, 131, 11, 1]}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (107, 7,1,'{"selected": "Male"}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (108, 8,1,'{"state": true}',ARRAY[100]);
INSERT INTO "values" (id,node_id,project_id,value,"order") VALUES (110,2,1,'{"name":"Item 1"}',1);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (113, 3,1,'{"content": "Casey Model"}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (114, 4,1,'{"figure": 49}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (115, 5,1,'{"date": "1976-10-10"}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (116, 6,1,'{"rgba": [210, 5, 5, 1]}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (117, 7,1,'{"selected": "Female"}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (118, 8,1,'{"state": false}',ARRAY[110]);
INSERT INTO "values" (id,node_id,project_id,value,"order") VALUES (120,2,1,'{"name":"Item 2"}',2);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (123, 3,1,'{"content": "Blair Mock"}',ARRAY[120]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (124, 4,1,'{"figure": 47}',ARRAY[120]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (125, 5,1,'{"date": "1977-07-01"}',ARRAY[120]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (126, 6,1,'{"rgba": [67, 147, 75, 1]}',ARRAY[120]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (127, 7,1,'{"selected": "Male"}',ARRAY[120]);
INSERT INTO "values" (id,node_id,project_id,value,list_path) VALUES (128, 8,1,'{"state": true}',ARRAY[120]);
SELECT setval('node_id_seq', 20);
SELECT setval('values_id_seq', 200);
