/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Node {
  editor: string | null;
  id: number;
  name: string | null;
  order: number | null;
  parent_id: number | null;
  type: string | null;
}

export interface DB {
  node: Node;
}
