/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Node {
	editor: string
	id: number
	name: string
	order: number
	parent_id: number | null
	type: string
}

export interface DB {
	node: Node
}
