BEGIN;
ALTER TABLE public.project ADD COLUMN version integer NOT NULL DEFAULT 0 CHECK (version >= 0);
ALTER TABLE public.node ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0);
ALTER TABLE public.node_settings ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0);
ALTER TABLE public."values" ADD COLUMN revision integer NOT NULL DEFAULT 1 CHECK (revision > 0);
CREATE FUNCTION public.bump_content_revision() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 NEW.revision := OLD.revision + 1;
 RETURN NEW;
END;
$$;
CREATE TRIGGER node_revision BEFORE UPDATE ON public.node FOR EACH ROW EXECUTE FUNCTION public.bump_content_revision();
CREATE TRIGGER settings_revision BEFORE UPDATE ON public.node_settings FOR EACH ROW EXECUTE FUNCTION public.bump_content_revision();
CREATE TRIGGER value_revision BEFORE UPDATE ON public."values" FOR EACH ROW EXECUTE FUNCTION public.bump_content_revision();
CREATE TABLE public.content_revision (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
 version integer NOT NULL CHECK (version >= 0),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 author_id text REFERENCES public."user"(id) ON DELETE SET NULL,
 author_name text NOT NULL,
 summary varchar(200) NOT NULL,
 snapshot jsonb NOT NULL,
 UNIQUE (project_id, version)
);
COMMIT;
