BEGIN;
UPDATE public.project_user SET roles = ARRAY[CASE
 WHEN owner THEN 'Owner'
 WHEN 'Admin' = ANY(roles) THEN 'Admin'
 WHEN 'Editor' = ANY(roles) THEN 'Editor'
 ELSE 'Viewer' END];
ALTER TABLE public.project_user ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE public.project_user ADD CONSTRAINT canonical_project_role CHECK (
 (owner AND confirmed AND roles = ARRAY['Owner']) OR
 (NOT owner AND roles IN (ARRAY['Admin'], ARRAY['Editor'], ARRAY['Viewer']))
);
CREATE UNIQUE INDEX one_owner_per_project ON public.project_user(project_id) WHERE owner;
CREATE TABLE public.project_invitation (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
 email text NOT NULL CHECK (email = lower(trim(email))),
 role text NOT NULL CHECK (role IN ('Admin', 'Editor', 'Viewer')),
 token_hash text NOT NULL UNIQUE,
 invited_by text REFERENCES public."user"(id) ON DELETE SET NULL,
 invited_name text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at timestamptz NOT NULL,
 accepted_at timestamptz,
 accepted_by text REFERENCES public."user"(id) ON DELETE SET NULL,
 revoked_at timestamptz
);
CREATE UNIQUE INDEX pending_project_invitation ON public.project_invitation(project_id, email)
 WHERE accepted_at IS NULL AND revoked_at IS NULL;
COMMIT;
