BEGIN;
-- Deliberately survives project deletion, so a failed storage request can be retried.
CREATE TABLE public.media_cleanup_job (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 prefix text NOT NULL CHECK (prefix ~ '^project_[0-9]+/$'),
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 attempts integer NOT NULL DEFAULT 0,
 not_before timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_error text
);
COMMIT;
