BEGIN;
ALTER TABLE public.content_revision ADD CONSTRAINT content_revision_project_identity UNIQUE(id, project_id);
ALTER TABLE public.project ADD COLUMN published_revision_id integer;
ALTER TABLE public.project ADD CONSTRAINT project_publication_revision
 FOREIGN KEY (published_revision_id, id) REFERENCES public.content_revision(id, project_id)
 ON DELETE SET NULL (published_revision_id);
ALTER TABLE public.api_key ADD COLUMN preview boolean NOT NULL DEFAULT false;
CREATE TABLE public.content_publication (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 project_id integer NOT NULL REFERENCES public.project(id) ON DELETE CASCADE,
 revision_id integer NOT NULL,
 author_id text REFERENCES public."user"(id) ON DELETE SET NULL,
 author_name text NOT NULL,
 created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (revision_id, project_id) REFERENCES public.content_revision(id, project_id) ON DELETE CASCADE
);
CREATE INDEX publication_history ON public.content_publication(project_id, id DESC);
COMMIT;
